[tool.poetry]
name = "auth-server"
version = "0.1.0"
description = ""
authors = ["Hugo Seabra <hugoseabra19@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
